### How to Speed up Pandas by 4x

In [1]:
import pandas as pd

## Read in the data with Pandas

In [2]:
%%time
df = pd.read_csv("esea_master_dmg_demos.part1.csv")

Wall time: 27.1 s

In [3]:
#Install                                    #Link: https://modin.readthedocs.io/en/latest/installation.html
#!pip install modin[ray]

In [4]:
### Read in the data with Modin
import modin.pandas as pd

In [5]:
import ray
ray.init()

2021-10-11 08:07:42,048	INFO services.py:1250 -- View the Ray dashboard at http://127.0.0.1:8265

{'node_ip_address': '192.168.1.16',
 'raylet_ip_address': '192.168.1.16',
 'redis_address': '192.168.1.16:6379',
 'object_store_address': 'tcp://127.0.0.1:64330',
 'raylet_socket_name': 'tcp://127.0.0.1:63780',
 'webui_url': '127.0.0.1:8265',
 'session_dir': 'C:\\Users\\MD550B~1.ATI\\AppData\\Local\\Temp\\ray\\session_2021-10-11_08-07-33_953595_9748',
 'metrics_export_port': 62052,
 'node_id': '78f3b7366fba6745ed07bb132ad4d2f2251d55b11c0ecf6855be9952'}

In [6]:
%%time
df = pd.read_csv("esea_master_dmg_demos.part1.csv")

Wall time: 19.6 s

In [7]:
import modin.pandas as pd

In [8]:
import modin.pandas as pd
import numpy as np

frame_data = np.random.randint(0, 100, size=(2**10, 2**8))
df = pd.DataFrame(frame_data)

UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.

In [9]:
df.shape

(1024, 256)

In [10]:
df.to_csv('test.csv')

In [11]:
%%time
import pandas as pd
pd.read_csv('https://raw.githubusercontent.com/MateLabs/Public-Datasets/master/Datasets/wine.csv')

(pid=13700) Windows fatal exception: access violation
(pid=13700)

Wall time: 402 ms

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,one
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,one
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,one
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,one
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,three
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,three
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,three
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,three
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,three

In [12]:
%%time
import modin.pandas as pd
pd.read_csv('https://raw.githubusercontent.com/MateLabs/Public-Datasets/master/Datasets/wine.csv')

UserWarning: Parameters provided defaulting to pandas implementation.
To request implementation, send an email to feature_requests@modin.org.

Wall time: 321 ms

,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline,Class
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,one
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,one
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,one
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,one
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,one
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740,three
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750,three
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835,three
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840,three
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560,three